### ISSUE TITLE
Regex Validity Check

### ISSUE THREAD

**Issue by lamwj98** [AY2122S2-CS2103T-W09-3/tp#55]
Following classes of regex check need to be change to fit the application better:
- Description
- Expense Category

To check the following regex is valid:
- Amount

**Comment by talkintomato** [comment]
the only limitation is that its expenses have to be alphanumeric which means that {}[]() etc, all cannot be used anywhere within the description and cat of the expense which is fine for now

An expansion would be to allow brackets and special characters but I feel like that may open up a lot of problems with parsing. For a cli centric build, it may be smarter to stick to the current alphanumeric restrictions

**Comment by talkintomato** [comment]
I agree i think the current regrex is sufficient
